name: build and push docker images

on:
  push:
    branches: [main]

env:
  FRONTEND_IMAGE_BASE: jorgeflorentino8/astrademo-frontend
  BACKEND_IMAGE_BASE: jorgeflorentino8/astrademo-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jorgeflorentino8
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image tag
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.FRONTEND_IMAGE_BASE }}:${{ env.IMAGE_TAG }}
            ${{ env.FRONTEND_IMAGE_BASE }}:latest

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.BACKEND_IMAGE_BASE }}:${{ env.IMAGE_TAG }}
            ${{ env.BACKEND_IMAGE_BASE }}:latest


