name: AstraOps Deploy

on:
  workflow_run:
    workflows: ["build and push docker images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AstraOps CLI
        run: npm install -g @astraops/astraops-cli

      - name: Ensure AstraOps CLI is in PATH
        run: astraops-cli help 

      - name: Deploy with AstraOps
        run: |
          astraops-cli -h
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          ASTRAOPS_API_KEY: ${{ secrets.ASTRAOPS_API_KEY }} 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}